### ISSUE TITLE
rate pid derivative filter applied to i_prev

### ISSUE THREAD

**Issue by magate** [elodin-sys/elodin#18]
https://github.com/elodin-sys/elodin/blob/a92068cb82972bbbe84a1633d4602ca3c8ed52ea/examples/drone/control.py#L223

Is this correct? The filter is being applied from the previous integral error to the new derivative value?

At first glance I think this needs a comment as it is not what I would expect.

**Comment by akhilles** [comment]
Ah, no. That's definitely a bug. It should be `d_prev`. Thanks for catching this. It effectively caused the integral gain to amplified and the derivative gain to be suppressed.

**Comment by akhilles** [comment]
Fixed in https://github.com/elodin-sys/elodin/commit/afb1a0a77a6c71d06d9265a331b4e4c60ecf1f6b.
