### ISSUE TITLE
Nox: no method named `as_flattened` found

### ISSUE THREAD

**Issue by alexlatif** [elodin-sys/elodin#19]
both ways of importing the library 

```
[dependencies]
nox = "0.4.0"
# nox = { git = "https://github.com/elodin-sys/elodin", package = "nox", features = ["xla", "noxpr"] }
```

both for as_flattened and as_flattened_mut with a total of 4 compiler errors. is there any way for me to use Nox atm?

**Comment by sphw** [comment]
`as_flattened` and `as_flattened_mut` were both added in Rust 1.80.0. So you'll have to update your Rust version. Running `rustup update` should do the trick. Sorry about not documenting the MSRV anywhere. We will add that soon

**Comment by sphw** [comment]
Let me know if that solved the problem for you. We can reopen if it didn't

**Comment by alexlatif** [comment]
Thank you very much @sphw. I love the library and would love to be able to extend or use AD for neural net expression. 

Thinking to add this as Burn backend for interchangeable Python transpilability for high level expression, yet found it on Rust as the main infra, training and inference logic (as well as net expression). Burn seems opposed to using XLA to eliminate C++ (reasonable), though I currently see no better way to have such close coupling to Python.

Apologies on the details not so relevant to this specific issue, but something I'd want to use this crate for and perhaps the conversation on how this part of the ecosystem could unify would be great.
